port: 7880
bind_addresses:
  - ""
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: false
turn:
  enabled: false
redis:
  address: redis:6379
keys:
  APIKeySecret_1234567890abcdef: abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890
webhook:
  api_key: APIKeySecret_1234567890abcdef
room:
  auto_create: true