# LiveKit Server Configuration
port: 7880
bind_addresses:
  - ""

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true

redis:
  address: redis:6379

keys:
  APIKeySecret_1234567890abcdef: abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890

turn:
  enabled: false

development: true