# LiveKit Server Configuration
port: 7880
bind_addresses:
  - ""

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50020
  use_external_ip: false
  node_ip: "127.0.0.1"
  stun_servers:
    - stun.l.google.com:19302

redis:
  address: redis:6379

keys:
  APIKeySecret_1234567890abcdef: abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890

turn:
  enabled: false

development: true
log_level: debug